spring.application.name=softbookstore

# Rules for Book Discount
app.book-discount.discountFor2Books=5
app.book-discount.discountFor3Books=10
app.book-discount.discountFor4Books=20
app.book-discount.discountFor5Books=25


# Books Master data
app.book-store.books[0].bookId=1001
app.book-store.books[0].title=Clean Code (Robert Martin, 2008)
app.book-store.books[0].price=50.0

app.book-store.books[1].bookId=1002
app.book-store.books[1].title=The Clean Coder (Robert Martin, 2011)
app.book-store.books[1].price=50.0

app.book-store.books[2].bookId=1003
app.book-store.books[2].title=Clean Architecture (Robert Martin, 2017)
app.book-store.books[2].price=50.0

app.book-store.books[3].bookId=1004
app.book-store.books[3].title=Test Driven Development by Example (Kent Beck, 2003)
app.book-store.books[3].price=50.0

app.book-store.books[4].bookId=1005
app.book-store.books[4].title=Working Effectively With Legacy Code (Michael C. Feathers, 2004)
app.book-store.books[4].price=50.0
