spring.application.name=softbookstore

# Rules for Book Discount
app.book-discount.discountFor2Books=5
app.book-discount.discountFor3Books=10
app.book-discount.discountFor4Books=20
app.book-discount.discountFor5Books=25
